export const NOTIFICATION_TEMPLATE_NAME = {
  EMAIL_VERIFICATION: 'EMAIL_VERIFICATION',
  PASSWORD_RESET: 'PASSWORD_RESET',
  GENERIC: 'GENERIC',
} as const;

export type NotificationTemplateName =
  (typeof NOTIFICATION_TEMPLATE_NAME)[keyof typeof NOTIFICATION_TEMPLATE_NAME];
