import {
  IsEmail,
  IsNotEmpty,
  IsOptional,
  IsString,
  IsUUID,
  MaxLength,
  MinLength,
} from 'class-validator';

/**
 * CreateUserDto — request body for POST /api/v1/users.
 *
 * Fields intentionally EXCLUDED — server-side only:
 *   nip             → auto-generated by NipHelper per role type
 *   passwordHash    → generated by UserService, never accepted from client
 *   mustChangePassword → always true on creation
 *   emailVerifiedAt → always null on creation
 *   deletedAt       → internal soft-delete field
 *   lastLoginAt     → updated on login
 *   tenantId        → extracted from JWT via @CurrentUser(), not from body
 */
export class CreateUserDto {
  @IsString()
  @IsNotEmpty()
  @MinLength(2)
  @MaxLength(100)
  name!: string;

  @IsEmail()
  @IsNotEmpty()
  @MaxLength(255)
  email!: string;

  @IsUUID()
  @IsNotEmpty()
  roleId!: string;

  @IsOptional()
  @IsString()
  @MaxLength(500)
  address?: string;

  @IsOptional()
  @IsString()
  @MaxLength(50)
  contact?: string;

  @IsOptional()
  @IsString()
  @MaxLength(500)
  avatarUrl?: string;
}
